name: crcrme_material_theme
description: The official Material theme for the CR-CRME.
repository: https://github.com/cr-crme/crcrme_flutter_template

version: 1.0.0+1

environment:
    sdk: ">=2.17.3 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    fonts:
        - family: Noto Sans
          fonts:
              - asset: fonts/NotoSans-Regular.ttf
              - asset: fonts/NotoSans-Italic.ttf
                style: italic
              - asset: fonts/NotoSans-Bold.ttf
              - asset: fonts/NotoSans-BoldItalic.ttf
                style: italic
